### ISSUE TITLE
I am unable to find project controls in appgain dashboard

### ISSUE THREAD

**Issue by arunabhverma** [appgain/react-native-appgain-sdk#7]
https://user-images.githubusercontent.com/59590144/118258376-63c3be00-b4cd-11eb-9025-3c68d344e611.png

**Comment by mohmagdy** [comment]
Project controls are on project settings if you mean: edit/delete project 
Please contact our support team via website chat on the dashboard or website appgain.io 

in addition, you can book a free product tour call on https://calendly.com/appgain/30min
